# Generated by Django 5.0.6 on 2024-05-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
