# Generated by Django 5.0.6 on 2024-05-27 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_movie_movie_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='number_in_stock',
        ),
        migrations.AddField(
            model_name='movie',
            name='about',
            field=models.TextField(blank=True),
        ),
    ]
